  
version: '3'
services:

  website-builder:
    image: node:16-alpine
    container_name: website-builder
    command: [sh, -c, "npm i && npm run dev"]
    ports:
      - "3000:3000"
    working_dir: '/app'
    tty: true
    volumes:
      - './:/app'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      SITE: example
      BASE: //localhost:3000